#!/usr/bin/env bash

NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

pushd "$HOME" >/dev/null
echo ""

echo -e "${CYAN}➜ Updating the dots repo origin URL${NOCOLOR}"
git --git-dir=$HOME/.dots/repo.git/ --work-tree=$HOME remote set-url origin "git@gitlab.com:tom81094/dots.git"

echo -e "${CYAN}➜ Init submodules${NOCOLOR}"
git --git-dir=$HOME/.dots/repo.git/ --work-tree=$HOME submodule update --recursive --remote --init

if command -v nvim >/dev/null 2>&1; then
    echo -e "${CYAN}➜ Bootstrapping neovim${NOCOLOR}"
    nvim '+PlugUpdate' '+PlugClean!' '+qa'
fi

if [[ ! -d "$HOME/.tmux/plugins" ]]; then
    echo -e "${CYAN}➜ Bootstrapping tmux${NOCOLOR}"
    git clone https://github.com/tmux-plugins/tpm.git $HOME/.tmux/plugins/tpm
fi

if [[ ! -d "$HOME/.forgit" ]]; then
    echo -e "${CYAN}➜ Bootstrapping forgit${NOCOLOR}"
    git clone https://github.com/wfxr/forgit.git $HOME/.forgit
fi

if [[ ! -f "$HOME"/.git-completion.bash ]]; then
    echo -e "${CYAN}➜ Install git bash completion for dots${NOCOLOR}"
    curl -o "$HOME"/.git-completion.bash https://git.kernel.org/pub/scm/git/git.git/plain/contrib/completion/git-completion.bash?h=maint
fi

if [[ ! -d "$HOME"/.linuxbrew ]]; then
    echo -e "${CYAN}➜ Install linuxbrew${NOCOLOR}"
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

if [[ ! -d "$HOME"/bin ]]; then
    mkdir -p "$HOME"/bin
fi

if [[ ! -f "$HOME"/bin/mc ]]; then
    echo -e "${CYAN}➜ Install minio client${NOCOLOR}"
    brew install minio-mc
fi

if [[ ! -f "$HOME"/bin/rke ]]; then
    echo -e "${CYAN}➜ Install rke client${NOCOLOR}"
    brew install rke
fi

if ! command -v ag >/dev/null; then
    echo -e "${CYAN}➜ Install silver searcher ag${NOCOLOR}"
    sudo apt-get install silversearcher-ag
    brew install the_silver_searcher
fi

if ! command -v arangosh >/dev/null; then
    echo -e "${CYAN}➜ Install arangodb3-client${NOCOLOR}"
sudo su <<EOF
curl -L "https://download.arangodb.com/arangodb36/DEBIAN/Release.key" | apt-key add -
echo 'deb https://download.arangodb.com/arangodb36/DEBIAN/ /' | tee /etc/apt/sources.list.d/arangodb.list
apt-get install apt-transport-https
apt-get update
apt-get install arangodb3-client
EOF
fi

if ! command -v pet >/dev/null; then
    echo -e "${CYAN}➜ Install pet${NOCOLOR}"
sudo su <<EOF
curl -LO "https://github.com/knqyf263/pet/releases/download/v0.3.0/pet_0.3.0_linux_amd64.deb"
dpkg -i pet_0.3.0_linux_amd64.deb
rm pet_0.3.0_linux_amd64.deb
EOF
fi

if ! command -v anyrc >/dev/null; then
    echo -e "${CYAN}➜ Install anyrc${NOCOLOR}"
    curl -sS https://raw.githubusercontent.com/amaya382/anyrc/0.0.2/install.sh | DIR="$HOME"/bin bash
    mkdir -p "$HOME"/.anyrc.d
fi

#echo "➜ Sourcing X11 files"
#[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
#[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

echo ""
popd >/dev/null
