#!/usr/bin/env bash

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          30
bspc config focus_follows_pointer true

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc rule -a 'Gimp' state=floating follow=on
bspc rule -a 'Kupfer'.py focus=on
bspc rule -a 'Pcmanfm' state=floating follow=on
bspc rule -a 'Pinentry' state=floating follow=on
bspc rule -a 'Scid' state=floating follow=on
bspc rule -a 'Screenkey' manage=off
bspc rule -a 'Steam' state=floating follow=on

bspc config normal_border_color '#262626'
bspc config focused_border_color '#d5c4a1'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#polybar top &
#GTK_IM_MODULE='ibus' XMODIFIERS='@im=ibus' QT_IM_MODULE='ibus' ibus-daemon -drx &
feh --bg-fill "$HOME/storage0/Images/Anime Wallpapers/62529718_p0.jpg" &
udiskie -t2 &

if [ $(pidof -x -o $$ bspwm | wc -w) -eq 1 ]; then
  nm-applet &
  pasystray &
  cadence --minimized &
  compton -o 0 -b --backend glx --vsync drm --xrender-sync --xrender-sync-fence
fi
